# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 19:29
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ssn',
            field=localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=localflavor.us.models.USStateField(default='NJ', max_length=2),
        ),
    ]
