# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 19:32
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170607_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
