# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170607_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dob',
            new_name='Date of birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128),
        ),
    ]
