# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170607_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ssn',
            new_name='SSN',
        ),
    ]
