# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170607_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(choices=[('selected', 'Selected'), ('drop', 'Drop'), ('pass', 'Pass'), ('fail', 'Fail')], max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('supervisor', models.CharField(max_length=128)),
                ('date of hire', models.DateField()),
                ('hourly_salary', models.PositiveIntegerField()),
                ('hours per week', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', localflavor.us.models.USStateField(default='NJ', max_length=2)),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('country', django_countries.fields.CountryField(blank=True, default='US', max_length=2)),
                ('work_phone', models.CharField(max_length=128)),
                ('work_phone_ext', models.CharField(max_length=128)),
                ('fax', models.CharField(max_length=128)),
                ('fringe benefits received', models.BooleanField()),
                ('covered by unemployment benefits', models.BooleanField()),
                ('placed_by', models.CharField(choices=[('school', 'School'), ('jcoet', 'JCOET'), ('self', 'Self'), ('other', 'Other')], max_length=128)),
                ('training_related', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='studentemployment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
