# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20170613_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date of birth',
            field=models.DateField(null=True),
        ),
    ]
