# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 04:44
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20170613_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SSN',
            field=localflavor.us.models.USSocialSecurityNumberField(max_length=11),
        ),
    ]
