# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20170613_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date of birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
