# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20170614_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='SSN',
            new_name='ssn',
        ),
    ]
