# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20170614_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(db_column='date of birth'),
        ),
    ]
