# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170614_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentemployment',
            name='covered by unemployment benefits',
        ),
        migrations.RemoveField(
            model_name='studentemployment',
            name='date of hire',
        ),
        migrations.RemoveField(
            model_name='studentemployment',
            name='fringe benefits received',
        ),
        migrations.RemoveField(
            model_name='studentemployment',
            name='hours per week',
        ),
        migrations.AddField(
            model_name='studentemployment',
            name='cbub',
            field=models.NullBooleanField(db_column='covered by unemployment benefits'),
        ),
        migrations.AddField(
            model_name='studentemployment',
            name='doh',
            field=models.DateField(blank=True, db_column='date of hire', null=True),
        ),
        migrations.AddField(
            model_name='studentemployment',
            name='fbr',
            field=models.NullBooleanField(db_column='fringe benefits received'),
        ),
        migrations.AddField(
            model_name='studentemployment',
            name='hpw',
            field=models.PositiveIntegerField(blank=True, db_column='hours per week', null=True),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='fax',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='hourly_salary',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='placed_by',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('jcoet', 'JCOET'), ('self', 'Self'), ('other', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, default='NJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='supervisor',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='training_related',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='work_phone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='studentemployment',
            name='work_phone_ext',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
