# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20170614_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentemployment',
            name='hourly_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
