# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20170618_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_status',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='accounting',
            field=models.CharField(blank=True, choices=[('compuaccounting', 'CompuAccounting'), ('compumedicaloa', 'CompuMedicalOA'), ('medical-coding', 'Medical-Coding'), ('medical-specialist', 'Medical-Specialist'), ('medical-coder', 'Medical-Coder')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='database',
            field=models.CharField(blank=True, choices=[('bioinfodatabase', 'BioInfoDatabase'), ('clinicalsa', 'ClinicalSA'), ('datawarehouse', 'DataWarehouse'), ('dbadminexpert ', 'DBAdminExpert '), ('dbdeveloper', 'DBDeveloper'), ('dbspecialist', 'DBSpecialist'), ('d/i-mssql7', 'D/I-MSSQL7'), ('e-commerce', 'e-Commerce'), ('hadoop', 'Hadoop'), ('db2-udb', 'DB2-UDB'), ('mcdba', 'MCDBA'), ('ms-sql-admin', 'MS-SQL-Admin'), ('oracle9i-oca', 'Oracle9i-OCA'), ('oracle9i-handson', 'Oracle9i-HandsOn'), ('oracle-clinicle', 'Oracle-Clinicle'), ('oracle9i-dba', 'Oracle9i-DBA'), ('oracle-developer', 'Oracle-Developer'), ('oracle-finance', 'Oracle-Finance'), ('oracle-finas', 'Oracle-FinAS'), ('oracle-ocp-dba', 'Oracle-OCP-DBA'), ('oracle9i-upgr', 'Oracle9i-Upgr')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='graphic',
            field=models.CharField(blank=True, choices=[('autocad', 'AutoCAD'), ('graphic-design', 'Graphic-Design'), ('flash', 'Flash'), ('html', 'HTML'), ('illustrator', 'Illustrator'), ('indesign', 'InDesign'), ('photoshop', 'PhotoShop'), ('quakexpress', 'QuakExpress'), ('imagegraphic', 'ImageGraphic')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='management',
            field=models.CharField(blank=True, choices=[('agile-scrum master', 'Agile-Scrum Master'), ('business analyst (ba)', 'Business Analyst (BA)'), ('pmp', 'PMP'), ('risk management project (rmp)', 'Risk Management Project (RMP)'), ('six sigma', 'Six Sigma')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='miscellaneous',
            field=models.CharField(blank=True, choices=[('nursing - cna', 'Nursing - CNA'), ('kid - debate team', 'Kid - Debate Team'), ('ekg', 'EKG'), ('emr', 'EMR'), ('kid - english enrichment', 'Kid - English Enrichment'), ('it auditing', 'IT Auditing'), ('job placement', 'Job Placement'), ('kid - math olympiads', 'Kid - Math Olympiads'), ('nursing - medassist', 'Nursing - MedAssist'), ('nursing - cmla', 'Nursing - CMLA'), ('nursing - medtrans', 'Nursing - MedTrans'), ('nursing - nurse ', 'Nursing - Nurse '), ('patient care tech', 'Patient Care Tech'), ('pharmacy tech', 'Pharmacy Tech'), ('kid - psat/sat/sat ii', 'Kid - PSAT/SAT/SAT II'), ('sap-bibo', 'SAP-BIBO'), ('sap-crm', 'SAP-CRM'), ('sap-fico', 'SAP-FICO'), ('sap-hr', 'SAP-HR'), ('sap-mm', 'SAP-MM'), ('summcamp', 'SummCamp'), ('sweepstakes', 'Sweepstakes')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='networking',
            field=models.CharField(blank=True, choices=[('ccna voice & security', 'CCNA Voice & Security'), ('checkpoint', 'CheckPoint'), ('ccie-iptelephony', 'CCIE-IPTelephony'), ('ccie-lab-routing', 'CCIE-Lab-Routing'), ('cciesecurity', 'CCIESecurity'), ('ccie-service provider', 'CCIE-Service Provider'), ('ccna', 'CCNA'), ('ccna-ccnp ', 'CCNA-CCNP '), ('ccnp', 'CCNP'), ('ciscoids', 'CiscoIDS'), ('ccie', 'CCIE'), ('cisco-iptelephony', 'Cisco-IPTelephony'), ('ciscopix', 'CiscoPIX'), ('ciscosecurity', 'CiscoSecurity'), ('cisco-checkpoint', 'Cisco-CheckPoint'), ('ciscovpn', 'CiscoVPN'), ('cissp', 'CISSP'), ('comptia security+', 'CompTIA Security+'), ('computer forensics', 'Computer Forensics'), ('internetsecurity', 'InternetSecurity'), ('ms security', 'MS Security'), ('net+', 'Net+'), ('pc/lan support', 'PC/LAN Support')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='office_skill',
            field=models.CharField(blank=True, choices=[('mos', 'MOS'), ('mous', 'MOUS'), ('mos-access', 'MOS-Access'), ('mos-access3 ', 'MOS-Access3 '), ('mos-access1', 'MOS-Access1'), ('mos-access2', 'MOS-Access2'), ('mos-excel3', 'MOS-Excel3'), ('mos-excel1', 'MOS-Excel1'), ('mos-excelcore', 'MOS-ExcelCore'), ('mos-excelexpert', 'MOS-ExcelExpert'), ('mos-excel2', 'MOS-Excel2'), ('mos-frontpage', 'MOS-FrontPage'), ('mos-outlook', 'MOS-Outlook'), ('mos-outlook3', 'MOS-Outlook3'), ('mos-outlook1', 'MOS-Outlook1'), ('mos-outlook2', 'MOS-Outlook2'), ('mos-powerpoint', 'MOS-PowerPoint'), ('mos-powerpoint3', 'MOS-PowerPoint3'), ('mos-powerpoint1', 'MOS-PowerPoint1'), ('mos-powerpoint2', 'MOS-PowerPoint2'), ('mos-word3', 'MOS-Word3'), ('mos-word1', 'MOS-Word1'), ('mos-word2', 'MOS-Word2'), ('msproject2003', 'MSProject2003')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='programming',
            field=models.CharField(blank=True, choices=[('j2ee-ww', 'J2EE-WW'), ('android mobile development', 'Android Mobile Development'), ('c#', 'C#'), ('ibm-websphere', 'IBM-Websphere'), ('java2-certificate', 'Java2-Certificate'), ('java-developer', 'Java-Developer'), ('c#-.net training', 'C#-.Net Training'), ('qa-automation ', 'QA-Automation '), ('qas-package', 'QAS-Package'), ('sas-package', 'SAS-Package'), ('siebel-6/7', 'Siebel-6/7'), ('software-specialist', 'Software-Specialist'), ('software-tester', 'Software-Tester'), ('sas', 'SAS'), ('vb.net', 'VB.Net'), ('vb-sql', 'VB-SQL'), ('web-ecommerce', 'Web-eCommerce')], max_length=128),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='system_admin',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('certified ethical hacking', 'Certified Ethical Hacking'), ('clientserver', 'ClientServer'), ('desktopapplication', 'DesktopApplication'), ('emc & san', 'EMC & SAN'), ('exchange2000', 'Exchange2000'), ('linux-sa', 'Linux-SA'), ('linux-workshop', 'Linux-Workshop'), ('mcitp', 'MCITP'), ('mcsa2003', 'MCSA2003'), ('mctsd2003', 'MCTSD2003'), ('mcse2000', 'MCSE2000'), ('mcse2003', 'MCSE2003'), ('sun-handson', 'Sun-HandsOn'), ('unix-sa', 'Unix-SA'), ('vmware', 'VMWare')], max_length=128),
        ),
    ]
