# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20170619_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='accounting',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='database',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='graphic',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='management',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='miscellaneous',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='networking',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='office_skill',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='programming',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='system_admin',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='students.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.CourseCategory'),
        ),
    ]
