# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20170620_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
