# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20170625_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cell_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='home_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='primary_phone',
            field=models.CharField(default=911, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_phone',
            field=models.CharField(default=411, max_length=16),
            preserve_default=False,
        ),
    ]
