COURSE_NAME_CHOICES = (('','----'), ('a+ pc technician', 'A+ PC Technician'), ('advance java/j2ee/weblogic/websphere', 'Advance Java/J2EE/Weblogic/Websphere'), ('agile-scrum master', 'Agile-Scrum Master'),
                       ('android mobile development', 'Android Mobile Development'), ('autocad', 'AutoCAD'), ('bio-info database training course', 'Bio-info Database Training course'),
                       ('business analyst (ba)', 'Business Analyst (BA)'), ('c# .net', 'C# .Net'), ('ccna voice', 'CCNA Voice'), ('certified ethical hacking', 'Certified Ethical Hacking'),
                       ('checkpoint security fireall course', 'Checkpoint Security Firewall Course'), ('cisco ccie ip telephony', 'Cisco CCIE IP Telephony'),
                       ('cisco ccie lab - routing & switch', 'Cisco CCIE Lab - Routing & Switch'), ('cisco ccie security', 'Cisco CCIE Security'),
                       ('cisco ccie training course', 'Cisco CCIE Training Course'), ('cisco ccna', 'Cisco CCNA'), ('cisco ccna & ccnp', 'Cisco CCNA & CCNP'),
                       ('cisco ccnp', 'Cisco CCNP'), ('cisco ids', 'Cisco IDS'), ('cisco intenet expert', 'Cisco Internet Expert'), ('cisco ip telephony', 'Cisco IP Telephony'),
                       ('cisco pix firewall security specialist', 'Cisco PIX Firewall Security Specialist'), ('cisco secure', 'Cisco Secure'),
                       ('cisco security & checkpoint security', 'Cisco Security & Check Point Security'), ('cisco vpn', 'Cisco VPN'), ('cissp', 'CISSP'),
                       ('client server specialist', 'Client Server Specialist'), ('clinical sa', 'Clinical SA'), ('cna', 'CNA'), ('comptia security+', 'CompTIA Security+'),
                       ('computer forensics', 'Computer Forensics'), ('computerized accounting specialist', 'Computerized Accounting Specialist'),
                       ('computerized medical office assistant', 'Computerized Medical Office Assistant'), ('data warehouse & cognos', 'Data Warehouse & Cognos'),
                       ('data administrator expert', 'Database Administrator Expert'), ('database developer', 'Database Developer'),
                       ('database specialist training', 'Database Specialist Training'), ('debate team', 'Debate Team'), ('design & implement database', 'Design & Implement Database'),
                       ('desktop application specialist', 'Desktop Application Specialist'), ('e-commerce package training course', 'E-Commerce Package Training Course'),
                       ('ekg', 'EKG'), ('emc & san', 'EMC & SAN'), ('emr', 'EMR'), ('english enrichment', 'English Enrichment'), ('exchange server 5000', 'Exchange Server 5000'),
                       ('grapich design', 'Graphic Design'), ('graphic design - flash', 'Graphic Design - Flash'), ('graphic design - html', 'Graphic Design - HTML'),
                       ('graphic design - illustrator', 'Graphic Design - Illustrator'), ('graphic design - indesign', 'Graphic Design - InDesign'),
                       ('graphic design - photoshop', 'Graphic Design - Photoshop'), ('graphic design - quak express', 'Graphic Design - Qwak Express'), ('hadoop', 'Hadoop'),
                       ('ibm db2 certificate program', 'IBM DB2 Certification Program'), ('ibm websphere program', 'IBM Websphere Program'),('image graphic design', 'Image Graphic Design'),
                       ('internet security specialist', 'Internet Security Specialist'), ('it auditing', 'IT Auditing'), ('it incubation', 'IT Incubation'),
                       ('java 2 certificate', 'Java 2 Certificate'), ('java developer package training', 'JAVA Developer Package Training'), ('job placement', 'Job Placement'),
                       ('linux sa', 'Linux SA'), ('linux sa workshop', 'Linux SA Workshop'), ('math olympiads', 'Math Olympiads'), ('mcitp', 'MCITP'),
                       ('mcsa windows 2003', 'MCSA Windows 2003'), ('mctsd windows 2003', 'MCTSD Windows 2003'), ('medical assistant', 'Medical Assistant'),
                       ('medical billing & coding specialist', 'Medical Billing & Coding Specialist'), ('medical billing specialist', 'Medical Billing Specialist'),
                       ('medical certified coder', 'Medical Certified Coder'), ('medical lab technician', 'Medical Lab Technician'), ('medical transcirpt', 'Medical Transcript'),
                       ('microsoft c# % .net training', 'Microsoft C# & .Net Training'), ('microsoft certified database admin', 'Microsoft Certified Database Admin'),
                       ('microsoft office specialists', 'Microsoft Office Specialists'), ('micorsoft user mous applications', 'Microsoft User MOUS Applications'),
                       ('mos access', 'MOS Access'), ('mos access advanced', 'MOS Access Advanced'), ('mos access beginner', 'MOS Access Beginner'),
                       ('mos access intermediate', 'MOS Access Intermediate'), ('mos excel advanced', 'MOS Excel Advance'), ('mos excel beginner', 'MOS Excel Beginner'),
                       ('mos excel core', 'MOS Excel Core'), ('mos excel expert', 'MOS Excel Expert'), ('mos excel intermediate', 'MOS Excel Intermediate'),
                       ('mos frontpage', 'MOS FrontPage'), ('mos outlook', 'MOS Outlook'), ('mos outlook advanced', 'MOS Outlook Advanced'), ('mos outlook beginner', 'MOS Outlook Beginner'),
                       ('mos outlook intermediate', 'MOS Outlook Intermediate'), ('mos powerpoint', 'MOS PowerPoint'), ('mos powerpoint advanced', 'MOS PowerPoint Advanced'),
                       ('mos powerpoint beginner', 'MOS Powerpoint Beginner'), ('mos powerpoint intermediate', 'MOS Powerpoint Intermediate'), ('mos word advanced', 'MOS Word Advanced'),
                       ('mos word beginner', 'MOS Word Beginner'), ('mos word intermediate', 'MOS Word Intermediate'), ('ms project 2003', 'MS Project 2003'), ('ms security', 'MS Security'),
                       ('ms sql admin', 'MS SQL Admin'), ('ms windows 2000', 'MS Windows 2000 MCSE'), ('ms windows 2000 mcse', 'MS Windows 2003 MCSE'), ('network+', 'Network+'),
                       ('nurse', 'Nurse'), ('oracle 9i database administrator', 'Oracle 9i Database Administrator'), ('oracle 9i hands-on project', 'Oracle 9i Hands-on Project'),
                       ('oracle clinical data management', 'Oracle Clinical Data Management'), ('oracle database administrator', 'Oracle Database Administrator'),
                       ('oracle developer/2000 & web application', 'Oracle Developer/2000 & Web Application'), ('oracle finance application server', 'Oracle Finance Application Server'),
                       ('oracle financial application server', 'Oracle Financial Application Server'), ('oracle oca/ocp dba', 'Oracle OCA/OCP DBA'),
                       ('oracle upgrade to 9i', 'Oracle Upgrade to 9i'), ('patient care tech', 'Patient Care Tech'), ('pc/lan help & Ssupport specialist', 'PC/LAN Help & Support Specialist'),
                       ('pharmacy tech', 'Pharmacy Tech'), ('project management training course', 'Project Management Training Course'), ('psat/sat/sat ii', 'PSAT/SAT/SAT II'),
                       ('quality assurance - automation', 'Quality Assurance - Automation'), ('quality assurance training package', 'Quality Assurance Training Package'),
                       ('risk management project (rmp)', 'Risk Management Project (RMP)'), ('sap-bibo', 'SAP-BIBO'), ('sap-crm', 'SAP-CRM'), ('sap-fico', 'SAP-FICO'), ('sap-hr', 'SAP-HR'),
                       ('sap-mm', 'SAP-MM'), ('sas training', 'SAS Training'), ('siebel(crm) 6/7 application', 'Siebel(CRM) 6/7 Application'), ('six sigma', 'Six Sigma'),
                       ('software specialist training program', 'Software Specialist Training Program'), ('software tester specialist', 'Software Tester Specialist'),
                       ('statistical Aaalyze specialist', 'Statistical Analyze Specialist'), ('summer camp', 'Summer Camp'), ('sun unix hands-on project', 'Sun Unix Hands-on Project'),
                       ('sweepstakes', 'Sweepstakes'), ('test', 'Test'), ('unix system administrator', 'Unix System Administrator'), ('vb.net', 'VB.NET'),
                       ('visual basic & sql server course', 'Visual Basic & SQL Server Course'), ('vmware', 'VMWare'),
                       ('web developer/e-commerce specialist', 'Web Developer/E-Commerce Specialist')
                       )
LOCATION_CHOICES = (('south_plainfield', 'South Plainfield'), ('hackensack', 'Hackensack'), ('fairfield', 'Fairfield'), ('eatontown', 'Eatentown'))
ROOM_CHOICES = (('A', 'South Plainfield A: CNA/MCSE'), ('B', 'South Plainfield B: SAS/.Net'), ('C', 'South Plainfield C: Cisco'), ('D', 'South Plainfield D: QA/.Net/Java'),
                ('E', 'South Plainfield E: Weblogic/Java/MCSE'), ('F', 'South Plainfield F: Unix/Linux'), ('G', 'South Plainfield G: Oracle/Clinic/Datawarehouse'))
START_TIME_CHOICES = (('eight-thirty am', '8:30 AM'), ('nine am', '9:00 AM'), ('nine-thirty am', '9:30 AM'), ('ten am', '10:00 AM'), ('ten-thirty am', '10:30 AM'), ('eleven am', '11:00 AM'),
                      ('eleven-thirty am', '11:30 AM'), ('twelve pm', '12:00 PM'), ('twelve-thirty pm', '12:30 PM'), ('one pm', '1:00 PM'), ('one-thirty pm', '1:30 PM'), ('two pm', '2:00 PM'),
                      ('two-thirty pm', '2:30 PM'), ('three pm', '3:00 PM'), ('three-thirty pm', '3:30 PM'), ('four pm', '4:00 PM'), ('four-thirty pm', '4:30 PM'), ('five pm', '5:00 PM'),
                      ('five-thirty pm', '5:30 PM'), ('six pm', '6:00 PM'), ('six-thirty pm', '6:30 PM'), ('seven pm', '7:00 PM'), ('seven-thirty pm', '7:30 PM'), ('eight pm', '8:00 PM'),
                      ('eight-thirty pm', '8:30 PM'), ('nine pm', '9:00 PM'), ('nine-thirty pm', '9:30 PM'), ('ten pm', '10:00 PM')
                      )
END_TIME_CHOICES = (('eight-thirty am', '8:30 AM'), ('nine am', '9:00 AM'), ('nine-thirty am', '9:30 AM'), ('ten am', '10:00 AM'), ('ten-thirty am', '10:30 AM'), ('eleven am', '11:00 AM'),
                      ('eleven-thirty am', '11:30 AM'), ('twelve pm', '12:00 PM'), ('twelve-thirty pm', '12:30 PM'), ('one pm', '1:00 PM'), ('one-thirty pm', '1:30 PM'), ('two pm', '2:00 PM'),
                      ('two-thirty pm', '2:30 PM'), ('three pm', '3:00 PM'), ('three-thirty pm', '3:30 PM'), ('four pm', '4:00 PM'), ('four-thirty pm', '4:30 PM'), ('five pm', '5:00 PM'),
                      ('five-thirty pm', '5:30 PM'), ('six pm', '6:00 PM'), ('six-thirty pm', '6:30 PM'), ('seven pm', '7:00 PM'), ('seven-thirty pm', '7:30 PM'), ('eight pm', '8:00 PM'),
                      ('eight-thirty pm', '8:30 PM'), ('nine pm', '9:00 PM'), ('nine-thirty pm', '9:30 PM'), ('ten pm', '10:00 PM')
                    )
INSTRUCTOR_CHOICES = (('','----'), ('adewale', 'Adewale Akinokun'), ('ajay', 'Ajay Kumar'), ('ajay_kumar', 'Ajay Kumar Bansal'), ('alexis', 'Alexis Valencia'), ('ana', 'Ana Johnson'), ('anand', 'Anand Chanchlani'),
                      ('andrew', 'Andrew Zhang'), ('anisa', 'Anisa Johnson'), ('anju', 'Anju Bhasin'), ('anna', 'Anna Johnson'), ('anthony', 'Anthony Boffice'), ('antonio', 'Antonio Terminiello'),
                      ('archana', 'Archana Seth'), ('ariel', 'Ariel Almacen'), ('arthur', 'Arthur Shebar'), ('ashok', 'Ashok Kalakota'), ('badar', 'Badar Sid'), ('brian', 'Brian Barretto'),
                      ('bruce', 'Bruce Cialfi'), ('camille', 'Camille Agama'), ('carla', 'Carla Fallone'), ('carol', 'Carol Ball'), ('carolyn', 'Carolyn Shelton'), ('chandra_p', 'Chandra Praba Botcha'),
                      ('chandra_s', 'Chandra Sekhar Botcha'), ('charles_b', 'Charles Beltran'), ('charles_h', 'Charles Huang'), ('charles_p', 'Charles Paver'), ('cleo', 'Cleo Ramos'),
                      ('cynthia_l', 'Cynthia Little'), ('cynthia_w', 'Cynthia Wang'), ('dan', 'Dan Mendoza'), ('david_pa', 'David Pascal'), ('david_pr', 'David Prowse'), ('david_s', 'David Sing'),
                      ('demitria', 'Demitria Orgo'), ('dennis', 'Dennis Lung'), ('devang', 'Devang Patel'), ('dmitriy', 'Dmitriy A. Krymchanskiy'), ('don', 'Don Hoffman'), ('donald', 'Donald Hsu'),
                      ('douglas', 'Dr. Douglas J. Bolton'), ('drew', 'Drew Beebe'), ('eddy', 'Eddy Li'), ('edward_m', 'Edward McCrae'), ('edward_c', 'Edward (Wonjun) Choi'), ('effie', 'Effie He'),
                      ('elie', 'Elie Phanor'), ('emil', 'Emil EJ Smith'), ('eric', 'Eric Silverstein'), ('erica', 'Erica James'), ('eugene', 'Eugene Bai'), ('eva', 'Eva Henry'), ('fawad', 'Fawad Khan'),
                      ('felice', 'Felice D'), ('frank_li', 'Frank Lin'), ('frank_lu', 'Frank Lu'), ('frederick', 'Frederick Miller'), ('gary_g', 'Gary Guan'), ('gary_m', 'Gary Mao'), ('gil', 'Gil Newman'),
                      ('gurudas', 'Gurudas Patil'), ('hai', 'Hai John Pan'), ('hector', 'Hector Reyes'), ('helen', 'Helen Njau'), ('henry', 'Henry Ma'), ('homiler', 'Homiler E Phanor'),
                      ('hongbing', 'Hongbing Ding'), ('hseng', 'Hseng Wee Ng'), ('irene_g', 'Irene Gerlovin'), ('irene_t', 'Irene Toufiles'), ('jack_w', 'Jack Wang'), ('jack_z', 'Jack Zhen'),
                      ('james', 'James Carr'), ('jamie', 'Jamie Juarbe'), ('jay', 'Jay Shyam N. Jayakumar'), ('jayan', 'Jayan M. Joseph'), ('jennifer_g', 'Jennifer Gwo'), ('jennifer_k', 'Jennifer Kiefer'), ('john_a', 'John Ao'),
                      ('john_k', 'John Kormos'), ('john_s', 'John Shorter'), ('jonathan_m', 'Jonathan Montgomery'), ('jonathan_y', 'Jonathan Yan'), ('joseph', 'Joseph Miao'), ('judith', 'Judith Rodgers'),
                      ('jun_r', 'Jun Reitman'), ('jun_w', 'Jun Wang'), ('katheleen', 'Katheleen Mouhanna'), ('keith', 'Keith A. Tice'), ('kin', 'Kin Chan'), ('lakshman', 'Lakshman P'),
                      ('larry', 'Larry Marden'),('laszio', 'Laszio Kopeczi-Boocz'), ('leonard', 'Leonard Lu'), ('logan', 'Logan Song'), ('lookman', 'Lookman Fazal'), ('louis_d', 'Louis DiPerna'),
                      ('louis_s', 'Louis Soto'), ('lu', 'Lu Zhang'), ('lulu', 'Lulu Hicks'), ('manpreet', 'Manpreet Singh'), ('manuel', 'Manuel Mesia'), ('marilyn', 'Marilyn Truppo'),
                      ('mark', 'Mark Brisson') ,('marnie', 'Marnie Vyff'), ('mary', 'Mary Jean Knoepfler'), ('maryann', 'Maryann Bouco'), ('mayen', 'Mayen Shah'), ('michael_f', 'Michael Fazio'),
                      ('michael_s', 'Michael Steirman'),  ('michael_v', 'Michael Vana'), ('mike_p', 'Mike Peters'), ('mike_c', 'Mike Chen Chen'), ('mohammed', 'Mohammed Shabber'),
                      ('nanak', 'Nanak Sawlani'), ('naomi', 'Naomi Sauer'), ('nihal', 'Nihal S.'), ('norman', 'Norman Stern'), ('om', 'Om Maduri'), ('patricia', 'Patricia Coccaro'),
                      ('paul_c', 'Paul Cirillo'), ('paul_k', 'Paul Krinzman'), ('peruma', 'Peruma Lakshman'), ('phil', 'Phil Crocker'), ('pratibha', 'Pratibha Bhat'), ('pravin', 'Pravin Ghandhi'),
                      ('rachanee', 'Rachanee Singprasong'), ('raghav', 'Raghav Seth'), ('raj_g', 'Raj Guttha'), ('raj_p', 'Raj Patel'), ('rajiv', 'Rajiv'), ('ralph', 'Ralph Walker'),
                      ('ramesh', 'Ramesh Chilukuri'), ('ramon', 'Ramon Toalombo'), ('randall', 'Randall Bratton'), ('rasheim', 'Rasheim Myers'), ('reeves', 'Reeves Alex'), ('regina', 'Regina Haber'),
                      ('richard', 'Richard Xue'), ('rick', 'Rick Chen'), ('rikesh', 'Rikesh Modi'), ('robert_b', 'Robert Bolmer'), ('robert_w', 'Robert William'), ('roberto', 'Roberto Lopez'),
                      ('rohit', 'Rohit Parti'), ('ron', 'Ron Carnicelli'), ('ruthie', 'Ruthie Yu'), ('sadia', 'Sadia Bhatti'), ('sairam', 'Sairam Nedunuri'), ('sajid', 'Sajid Abbasi'),
                      ('sakthi', 'Sakthi Pichaimani'), ('samira', 'Samira Bagh'), ('sandra', 'Sandra Anojulu'), ('sarah', 'Sarah Diroff'), ('scott', 'Scott Zhu'), ('sean', 'Sean Kim'),
                      ('sekhar', 'Sekhar Pandit'), ('shabbir', 'Shabbir Jariwala'), ('shabuddin', 'Shabuddin Sheik'), ('shyam', 'Shyam Jay Kumar'), ('sid', 'Sid Badar'), ('stela', 'Stela Anguelova'),
                      ('steve_a', 'Steve Ajmeri'), ('steve_h', 'Steve Hill'), ('steve_y', 'Steve Yang'), ('steven', 'Steven Schilling'), ('subarau', 'Subarau 0'), ('subramaniam', 'Subramaniam Tangiral'),
                      ('sue', 'Sue Chung'), ('surva', 'Surva Datta'), ('sushma', 'Sushma Chopra'), ('syed_a', 'Syed Ali'), ('syed_f', 'Syed Fouad Hussaim'), ('theresa', 'Theresa Desauliniers'),
                      ('thomas', 'Thomas Gan'), ('thushyanthy', 'Thushyanthy Balasingham'), ('tom', 'Tom Qu'), ('vanessa', 'Vanessa Brownfield-Bynum'), ('venkat_n', 'Venkat Navaneethakrishnan'),
                      ('venkat_r', 'Venkat Radhakrishnan'), ('verona', 'Verona Bassaragh-McKay'), ('vickie', 'Vickie Eaton'), ('vijaykumar', 'Vijaykumar Allampalli'), ('vikas', 'Vikas Seth'),
                      ('wally', 'Wally Ero-Phillips'), ('wei', 'Wei Gao'), ('yu', 'Yu Shen Sean Wang'), ('zhenda', 'Zhenda Xing')
                      )
TOTAL_HOURS_CHOICES = (('six', '6'), ('ten', '10'), ('twelve', '12'), ('twenty', '20'), ('twenty-four', '24'), ('twenty-five', '25'), ('twenty-eight', '28'), ('thirty', '30'), ('thirty-two', '32'),
                       ('thirty-five', '35'), ('forty', '40'), ('forty-five', '45'), ('fifty', '50'), ('sixty', '60'), ('seventy', '70'), ('seventy-five', '75'), ('eighty', '80'), ('ninety', '90'),
                       ('ninety-six', '96'), ('hundred', '100'), ('one-twenty', '120'), ('one-fifty', '150'), ('one-sixty', '160'), ('one-eighty', '180'), ('two-hundred', '200'), ('two-forty', '240'),
                       ('two-fifty', '250'), ('two-eighty', '280'), ('three-hundred', '300'), ('three-twenty', '320'), ('three-sixty', '360'), ('four-hundred', '400'), ('four-twenty', '420'),
                       ('four-eighty', '480'), ('seven-hundred', '700'), ('nine-eighty', '980'), ('fourteen-forty', '1440')
                       )
HOURS_PER_CLASS_CHOICES = (('two_and_half', '2.5'), ('three', '3'), ('four', '4'), ('four_and_half', '4.5'), ('five', '5'), ('six', '6'), ('seven', '7'), ('seven_and_half', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'))
FREQUENCY_CHOICES = (('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'))
STATUS_CHOICES = (('active', 'Active'), ('pending', 'Pending'))
INTERVAL_CHOICES = (('1 day', '1 Day'), ('2 days', '2 Days'), ('3 days', '3 Days'), ('4 days', '4 Days'), ('5 days', '5 Days'), ('6 days', '6 Days'), ('1 week', '1 Week'),
                    ('2 weeks', '2 Weeks'), ('3 weeks', '3 Weeks'), ('4 weeks', '4 Weeks'), ('5 weeks', '5 Weeks'), ('6 weeks', '6 Weeks'), ('8 weeks', '8 Weeks'), ('12 weeks', '12 Weeks')
                    )
TYPE_CHOICES = (('internal', 'Internal'), ('external', 'External'))
INSTRUCTOR_STATUS_CHOICES = (('active', 'Active'), ('inactive', 'Inactive'), ('unknown', 'Unknown'), ('expired', 'Expired'))