# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedules_initiated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='initiated_by',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
