# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedules_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule_id',
            field=models.IntegerField(default=0),
        ),
    ]
