# Student model choices
GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
BACKGROUND_CHOICES = (('beginner', 'Beginner'), ('networking 1', 'Networking 1'), ('networking 2', 'Networking 2'), ('programmer 1', 'Programmer 1'), ('programmer 2', 'Programmer 2'), ('database 1', 'Database 1'), ('database 2', 'Database 2'))
LOCATION_CHOICES = (('eatontown', 'Eatontown'), ('fairfield', 'Fairfield'), ('hackensack', 'Hackensack'), ('south_plainfield', 'South Plainfield'), ('shanghai', 'Shanghai'), ('nanning', 'Nanning'), ('piscataway', 'Piscataway'))
WORKFORCE_CHOICES = (('--', '--'), ('atlantic', 'Atlantic'), ('bergen', 'Bergen'), ('burlington', 'Burlington'), ('camden', 'Camden'), ('essex', 'Essex'), ('hudson', 'Hudson'), ('mercer', 'Mercer'), ('middlesex', 'Middlesex'), ('monmouth', 'Monmouth'), ('morris', 'Morris'), ('nyc', 'NYC'), ('ocean', 'Ocean'), ('passaic', 'Passaic'), ('pennsylvania', 'Pennsylvania'), ('salem', 'Salem'), ('somerset', 'Somerset'), ('sussex', 'Sussex'), ('union', 'Union'), ('warren', 'Warren'))
SOURCE_CHOICES = (('individual', 'Individual'), ('sylvan prometric/vue', 'Sylvan Prometric/VUE'), ('employment & training', 'Employment & Training'), ('member of chamber', 'Member of Chamber'), ('student visa f1', 'Student Visa F1'), ('instructor', 'Instructor'), ('avtech staff', 'Avtech Staff'), ('mo student', 'Mo student'), ('computertrainingguide', 'ComputerTrainingGuide'), ('corporate account', 'Corporate Account'), ('web register', 'Web Register'), ('students from act!', 'Students from ACT!'), ('dol - wia', 'DOL - WIA'), ('dol - wdp', 'DOL - WDP'), ('computer user', 'Computer User'), ('job guide', 'Job Guide'), ('desi talk', 'Desi Talk'), ('little india', 'Little India'), ('china press', 'China Press'), ('do wei', 'Do Wei'))
REFER_BY_CHOICES = (('alphatrain', 'AlphaTrain'), ('china press', 'China Press'), ('chinese express', 'Chinese Express'), ('chinese weekly', 'Chinese Weekly'), ('chinese world journal', 'Chinese World Journal'), ('computer user', 'Computer User'), ('county office', 'County Office'), ('desi talk', 'Desi Talk'), ('duowei times', 'Duowei Times'), ('flier', 'Flier'), ('friend', 'Friend'), ('internet', 'Internet'), ('job guide', 'Job Guide'), ('no refer', 'No Refer'), ('star ledger', 'Star Ledger'))
LAST_STATUS_CHOICES = (('followup', 'FollowUp'), ('sale', 'Sale'), ('nosale', 'NoSale'))


# StudentEmployment model choices
PLACED_BY_CHOICES = (('school', 'School'), ('jcoet', 'JCOET'), ('self', 'Self'), ('other', 'Other'))

# StudentCourse model choices
NETWORKING_CHOICES = (('ccna voice & security', 'CCNA Voice & Security'), ('checkpoint', 'CheckPoint'), ('ccie-iptelephony', 'CCIE-IPTelephony'), ('ccie-lab-routing', 'CCIE-Lab-Routing'), ('cciesecurity', 'CCIESecurity'), ('ccie-service provider', 'CCIE-Service Provider'), ('ccna', 'CCNA'), ('ccna-ccnp ', 'CCNA-CCNP '), ('ccnp', 'CCNP'), ('ciscoids', 'CiscoIDS'), ('ccie', 'CCIE'), ('cisco-iptelephony', 'Cisco-IPTelephony'), ('ciscopix', 'CiscoPIX'), ('ciscosecurity', 'CiscoSecurity'), ('cisco-checkpoint', 'Cisco-CheckPoint'), ('ciscovpn', 'CiscoVPN'), ('cissp', 'CISSP'), ('comptia security+', 'CompTIA Security+'), ('computer forensics', 'Computer Forensics'), ('internetsecurity', 'InternetSecurity'), ('ms security', 'MS Security'), ('net+', 'Net+'), ('pc/lan support', 'PC/LAN Support'))
SYSTEM_ADMIN_CHOICES = (('a+', 'A+'), ('certified ethical hacking', 'Certified Ethical Hacking'), ('clientserver', 'ClientServer'), ('desktopapplication', 'DesktopApplication'), ('emc & san', 'EMC & SAN'), ('exchange2000', 'Exchange2000'), ('linux-sa', 'Linux-SA'), ('linux-workshop', 'Linux-Workshop'), ('mcitp', 'MCITP'), ('mcsa2003', 'MCSA2003'), ('mctsd2003', 'MCTSD2003'), ('mcse2000', 'MCSE2000'), ('mcse2003', 'MCSE2003'), ('sun-handson', 'Sun-HandsOn'), ('unix-sa', 'Unix-SA'), ('vmware', 'VMWare'))
DATABASE_CHOICES = (('bioinfodatabase', 'BioInfoDatabase'), ('clinicalsa', 'ClinicalSA'), ('datawarehouse', 'DataWarehouse'), ('dbadminexpert ', 'DBAdminExpert '), ('dbdeveloper', 'DBDeveloper'), ('dbspecialist', 'DBSpecialist'), ('d/i-mssql7', 'D/I-MSSQL7'), ('e-commerce', 'e-Commerce'), ('hadoop', 'Hadoop'), ('db2-udb', 'DB2-UDB'), ('mcdba', 'MCDBA'), ('ms-sql-admin', 'MS-SQL-Admin'), ('oracle9i-oca', 'Oracle9i-OCA'), ('oracle9i-handson', 'Oracle9i-HandsOn'), ('oracle-clinicle', 'Oracle-Clinicle'), ('oracle9i-dba', 'Oracle9i-DBA'), ('oracle-developer', 'Oracle-Developer'), ('oracle-finance', 'Oracle-Finance'), ('oracle-finas', 'Oracle-FinAS'), ('oracle-ocp-dba', 'Oracle-OCP-DBA'), ('oracle9i-upgr', 'Oracle9i-Upgr'))
PROGRAMMING_CHOICES = (('j2ee-ww', 'J2EE-WW'), ('android mobile development', 'Android Mobile Development'), ('c#', 'C#'), ('ibm-websphere', 'IBM-Websphere'), ('java2-certificate', 'Java2-Certificate'), ('java-developer', 'Java-Developer'), ('c#-.net training', 'C#-.Net Training'), ('qa-automation ', 'QA-Automation '), ('qas-package', 'QAS-Package'), ('sas-package', 'SAS-Package'), ('siebel-6/7', 'Siebel-6/7'), ('software-specialist', 'Software-Specialist'), ('software-tester', 'Software-Tester'), ('sas', 'SAS'), ('vb.net', 'VB.Net'), ('vb-sql', 'VB-SQL'), ('web-ecommerce', 'Web-eCommerce'))
ACCOUNTING_CHOICES = (('compuaccounting', 'CompuAccounting'), ('compumedicaloa', 'CompuMedicalOA'), ('medical-coding', 'Medical-Coding'), ('medical-specialist', 'Medical-Specialist'), ('medical-coder', 'Medical-Coder'))
OFFICE_SKILL_CHOICES = (('mos', 'MOS'), ('mous', 'MOUS'), ('mos-access', 'MOS-Access'), ('mos-access3 ', 'MOS-Access3 '), ('mos-access1', 'MOS-Access1'), ('mos-access2', 'MOS-Access2'), ('mos-excel3', 'MOS-Excel3'), ('mos-excel1', 'MOS-Excel1'), ('mos-excelcore', 'MOS-ExcelCore'), ('mos-excelexpert', 'MOS-ExcelExpert'), ('mos-excel2', 'MOS-Excel2'), ('mos-frontpage', 'MOS-FrontPage'), ('mos-outlook', 'MOS-Outlook'), ('mos-outlook3', 'MOS-Outlook3'), ('mos-outlook1', 'MOS-Outlook1'), ('mos-outlook2', 'MOS-Outlook2'), ('mos-powerpoint', 'MOS-PowerPoint'), ('mos-powerpoint3', 'MOS-PowerPoint3'), ('mos-powerpoint1', 'MOS-PowerPoint1'), ('mos-powerpoint2', 'MOS-PowerPoint2'), ('mos-word3', 'MOS-Word3'), ('mos-word1', 'MOS-Word1'), ('mos-word2', 'MOS-Word2'), ('msproject2003', 'MSProject2003'))
GRAPHIC_CHOICES = (('autocad', 'AutoCAD'), ('graphic-design', 'Graphic-Design'), ('flash', 'Flash'), ('html', 'HTML'), ('illustrator', 'Illustrator'), ('indesign', 'InDesign'), ('photoshop', 'PhotoShop'), ('quakexpress', 'QuakExpress'), ('imagegraphic', 'ImageGraphic'))
MANAGEMENT_CHOICES = (('agile-scrum master', 'Agile-Scrum Master'), ('business analyst (ba)', 'Business Analyst (BA)'), ('pmp', 'PMP'), ('risk management project (rmp)', 'Risk Management Project (RMP)'), ('six sigma', 'Six Sigma'))
MISCELLANEOUS_CHOICES = (('nursing - cna', 'Nursing - CNA'), ('kid - debate team', 'Kid - Debate Team'), ('ekg', 'EKG'), ('emr', 'EMR'), ('kid - english enrichment', 'Kid - English Enrichment'), ('it auditing', 'IT Auditing'), ('job placement', 'Job Placement'), ('kid - math olympiads', 'Kid - Math Olympiads'), ('nursing - medassist', 'Nursing - MedAssist'), ('nursing - cmla', 'Nursing - CMLA'), ('nursing - medtrans', 'Nursing - MedTrans'), ('nursing - nurse ', 'Nursing - Nurse '), ('patient care tech', 'Patient Care Tech'), ('pharmacy tech', 'Pharmacy Tech'), ('kid - psat/sat/sat ii', 'Kid - PSAT/SAT/SAT II'), ('sap-bibo', 'SAP-BIBO'), ('sap-crm', 'SAP-CRM'), ('sap-fico', 'SAP-FICO'), ('sap-hr', 'SAP-HR'), ('sap-mm', 'SAP-MM'), ('summcamp', 'SummCamp'), ('sweepstakes', 'Sweepstakes'))

# Student_search form choices
STUDENT_SEARCH_COURSES = (('','----'), ('ccna voice & security', 'CCNA Voice & Security'), ('checkpoint', 'CheckPoint'), ('ccie-iptelephony', 'CCIE-IPTelephony'), ('ccie-lab-routing', 'CCIE-Lab-Routing'), ('cciesecurity', 'CCIESecurity'), ('ccie-service provider', 'CCIE-Service Provider'), ('ccna', 'CCNA'), ('ccna-ccnp ', 'CCNA-CCNP '), ('ccnp', 'CCNP'), ('ciscoids', 'CiscoIDS'), ('ccie', 'CCIE'), ('cisco-iptelephony', 'Cisco-IPTelephony'), ('ciscopix', 'CiscoPIX'), ('ciscosecurity', 'CiscoSecurity'), ('cisco-checkpoint', 'Cisco-CheckPoint'), ('ciscovpn', 'CiscoVPN'), ('cissp', 'CISSP'), ('comptia security+', 'CompTIA Security+'), ('computer forensics', 'Computer Forensics'), ('internetsecurity', 'InternetSecurity'), ('ms security', 'MS Security'), ('net+', 'Net+'), ('pc/lan support', 'PC/LAN Support'), ('a+', 'A+'), ('certified ethical hacking', 'Certified Ethical Hacking'), ('clientserver', 'ClientServer'), ('desktopapplication', 'DesktopApplication'), ('emc & san', 'EMC & SAN'), ('exchange2000', 'Exchange2000'), ('linux-sa', 'Linux-SA'), ('linux-workshop', 'Linux-Workshop'), ('mcitp', 'MCITP'), ('mcsa2003', 'MCSA2003'), ('mctsd2003', 'MCTSD2003'), ('mcse2000', 'MCSE2000'), ('mcse2003', 'MCSE2003'), ('sun-handson', 'Sun-HandsOn'), ('unix-sa', 'Unix-SA'), ('vmware', 'VMWare'), ('bioinfodatabase', 'BioInfoDatabase'), ('clinicalsa', 'ClinicalSA'), ('datawarehouse', 'DataWarehouse'), ('dbadminexpert ', 'DBAdminExpert '), ('dbdeveloper', 'DBDeveloper'), ('dbspecialist', 'DBSpecialist'), ('d/i-mssql7', 'D/I-MSSQL7'), ('e-commerce', 'e-Commerce'), ('hadoop', 'Hadoop'), ('db2-udb', 'DB2-UDB'), ('mcdba', 'MCDBA'), ('ms-sql-admin', 'MS-SQL-Admin'), ('oracle9i-oca', 'Oracle9i-OCA'), ('oracle9i-handson', 'Oracle9i-HandsOn'), ('oracle-clinicle', 'Oracle-Clinicle'), ('oracle9i-dba', 'Oracle9i-DBA'), ('oracle-developer', 'Oracle-Developer'), ('oracle-finance', 'Oracle-Finance'), ('oracle-finas', 'Oracle-FinAS'), ('oracle-ocp-dba', 'Oracle-OCP-DBA'), ('oracle9i-upgr', 'Oracle9i-Upgr'), ('mos', 'MOS'), ('mous', 'MOUS'), ('mos-access', 'MOS-Access'), ('mos-access3 ', 'MOS-Access3 '), ('mos-access1', 'MOS-Access1'), ('mos-access2', 'MOS-Access2'), ('mos-excel3', 'MOS-Excel3'), ('mos-excel1', 'MOS-Excel1'), ('mos-excelcore', 'MOS-ExcelCore'), ('mos-excelexpert', 'MOS-ExcelExpert'), ('mos-excel2', 'MOS-Excel2'), ('mos-frontpage', 'MOS-FrontPage'), ('mos-outlook', 'MOS-Outlook'), ('mos-outlook3', 'MOS-Outlook3'), ('mos-outlook1', 'MOS-Outlook1'), ('mos-outlook2', 'MOS-Outlook2'), ('mos-powerpoint', 'MOS-PowerPoint'), ('mos-powerpoint3', 'MOS-PowerPoint3'), ('mos-powerpoint1', 'MOS-PowerPoint1'), ('mos-powerpoint2', 'MOS-PowerPoint2'), ('mos-word3', 'MOS-Word3'), ('mos-word1', 'MOS-Word1'), ('mos-word2', 'MOS-Word2'), ('msproject2003', 'MSProject2003'))

STUDENT_SEARCH_LOCATION_CHOICES = (('', '----'), ('eatontown', 'Eatontown'), ('fairfield', 'Fairfield'), ('hackensack', 'Hackensack'), ('south_plainfield', 'South Plainfield'), ('shanghai', 'Shanghai'), ('nanning', 'Nanning'), ('piscataway', 'Piscataway'))

STUDENT_SEARCH_GENDER_CHOICES = (('','----'), ('M', 'Male'), ('F', 'Female'))